#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
# Enables management via the init script.

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# INSTALL HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver web-01 54.237.52.200 check\n\tserver web-02 34.224.62.212 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart

