#!/usr/bin/env bash
# Find the error and make Nginx Server to listen on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled-default
service nginx restart
