#!/usr/bin/env bash
# This script configures an Nginx server to listen on port 80.

# Remove the default configuration file
rm -rf /etc/nginx/sites-enabled/default

# Create a symbolic link for the default configuration file in the sites-enabled directory
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
service nginx restart

