#!/usr/bin/env bash

# Gracefully reload Gunicorn

# Find the process ID (PID) of the Gunicorn master process
PID=$(pgrep -f "gunicorn --bind 0.0.0.0:5003 web_dynamic.2-hbnb:app")

if [[ -n $PID ]]; then
  echo "Reloading Gunicorn gracefully (PID: $PID)..."
  kill -HUP "$PID"
  echo "Gunicorn reloaded successfully."
else
  echo "Gunicorn is not running or could not find the PID."
fi
